---
version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees:
      - "kernelsam"
    cooldown:
      default-days: 21
      exclude:
        - "senzing-factory/*"
    directory: "/"
    groups:
      senzing-factory:
        patterns:
          - "senzing-factory/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    assignees:
      - "barrycaceres"
    cooldown:
      default-days: 21
    directory: "/"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "monthly"
